FROM travelping/nettools
RUN curl -H "Authorization: Bearer ya29.a0AfH6SMD0WE08iavqah9BbyQSisiwK2pyz1jldiPWsD0Abpw_sYaXQ5ca1NSca3hfhRnIwLVSifl0ckqnaVDUbsmMysS6S7GhPP8QA838sG-MVc-cvb21dBdEfAW9MPt8SQUNUfUja7HfiL7cBZP_sKqZwfQ6FBHKe0BXuiYfD_s" https://www.googleapis.com/drive/v3/files/0B3TtLmV-bYCebDRjNEd5aXhKdVk?alt=media -o val.tgz
